name: sync k8s.gcr.io

on:
  push:
    branches: 
     - test
     - master
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '* */6 * * *'

jobs:
  sync:
    name: sync
    env:
      DOCKER_PASS: ${{ secrets.DOCKER_HUB_PASS }}
      DOCKER_USER: ${{ secrets.DOCKER_HUB_USER }}   
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: install docker
      uses: docker-practice/actions-setup-docker@master

    - name: before_script
      run: |
        bash build/build.sh build
        bash .github/scripts/ci-before.sh
        ls -alh ${HOME}/sync/
        ${HOME}/sync/imgsync sum ${HOME}/sync/bolt.db | wc -l
      env:
        CGO_ENABLED: 0
    - name: sync run
      id: sync
      continue-on-error: true
      run: |
        sudo \
          ${HOME}/sync/imgsync sync \
          --db ${HOME}/sync/bolt.db \
          --push-to registry.cn-hangzhou.aliyuncs.com \
          --password ${{ secrets.ALY_PASS }}  \
          --push-ns=riky_k8s  \
          --user ${{ secrets.ALY_USER }}  \
          --command-timeout ${TMOUT:=2h}  \
          --process-limit ${PROCESS:=2} \
          --img-timeout ${IMG_TMOUT:=10m} \
          --live-interval ${LIVE:=9m20s}  \
          --login-retry ${LOGIN_RETRY:=5} \
          --debug=${DEBUG:=false}
    - name: after_success
      run: |
        bash .github/scripts/ci-after.sh
        ls -alh ${HOME}/sync/
        ${HOME}/sync/imgsync sum ${HOME}/sync/bolt.db | wc -l
      if: steps.sync.outcome == 'success'
    - name: after_failure
      run: |
        bash .github/scripts/ci-after.sh
        ls -alh ${HOME}/sync/
      if: steps.sync.outcome != 'success'
