name: sync k8s.gcr.io

on:
  push:
    branches: 
     - test
     - master
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    env:
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }} 
    runs-on: ubuntu-latest
    steps:

    - name: script
      id: test1
      continue-on-error: true
      run: |
        ls -l sadasd
        
    - name: script
      id: sync
      continue-on-error: true
      run: |
        ls -l
        
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
      
    - name: after_success
      run: |
        echo success
      if: ${{ steps.sync.outcome }} == 'success'
    - name: after_failure
      run: |
        echo failure
      if: ${{ steps.sync.outcome }} != 'success'
